[package]
name = "eightchip"
version = "0.1.0"
authors = ["Pedro Castilho <cstl.px@gmail.com>"]

[dependencies]
gfx = "0.16"
synth = "0.10"
glutin = "0.8"
gfx_window_glutin = "0.16"

[dev_dependencies]
quickcheck = "0.4"

[profile.release]
lto = true
panic = 'abort'
