[package]
name = "eightchip"
version = "0.1.0"
authors = ["Pedro Castilho <cstl.px@gmail.com>"]

[dependencies]
gfx = "0.13"
synth = "0.10"
glfw = "*"
gfx_window_glfw = "*"

[dev_dependencies]
quickcheck = "0.4"

[profile.release]
lto = true
panic = 'abort'
